from enum import Enum


class Columns(Enum):
    IP_ADDRESS = "IP_ADDRESS"
    COOKIE_ID = "COOKIE_ID"
    USER_ID = "USER_ID"
    TIMESTAMP = "TIMESTAMP"
    REQUEST_METHOD = "REQUEST_METHOD"
    REQUEST_URL = "REQUEST_URL"
    HTTP_VERSION = "HTTP_VERSION"
    HTTP_STATUS = "HTTP_STATUS"
    FILE_SIZE = "FILE_SIZE"
    REFERER = "REFERER"
    USER_AGENT = "USER_AGENT"
    UNIX_TIME = "UNIX_TIME"
